### ISSUE TITLE
Make editable fosters/volunteers

### ISSUE THREAD

**Issue by PranovD** [PranovD/LLOV#43]

**Comment by PranovD** [comment]
- [ ] Create Editable Button

- [ ] Create Pop Up

- [ ] Populate Pop Up w/ Previous Data

- [ ] Allow data to be sent back to Database

- [ ] Create Button to delete

- [ ] Create warning pop up (Are you sure?)

- [ ] Allow Data to delete from database

**Comment by Varun-Ballari** [comment]
instead of warning pop up, we decided to use a password
