### ISSUE TITLE
Fix Jinja Templating Syntax Errors

### ISSUE THREAD

**Issue by megmay** [PranovD/LLOV#52]
[] Wait for issue #51 & #49 to be completed (we can't fix syntax if we haven't first figured out how we're handling/parsing JSON objects)

[] Consult with @PranovD, @megmay, & @Varun-Ballari to make sure everyone is on board with how we are going to handle/parse JSON objects from FireBase (quick GroupMe msg?)

[] Fix the Jinja templating syntax errors that are currently highlighted out in most of the templates

**Comment by NilayMehta** [comment]
Parse Json objects with Jinja to reflect changes to Database on front end
